version: 2

models:
  - name: fct_messages
    columns:
      - name: message_id
        tests: [not_null, unique]
      - name: has_image
        tests: [not_null]

  - name: dim_channels
    columns:
      - name: channel_key
        tests: [not_null, unique]

  - name: dim_dates
    columns:
      - name: date
        tests: [not_null, unique]
