"""add product_name column

Revision ID: 83a2eeffdb5f
Revises: 6721460428c4
Create Date: 2025-08-18 21:02:29.442485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83a2eeffdb5f'
down_revision: Union[str, Sequence[str], None] = '6721460428c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_channels',
    sa.Column('channel_key', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('channel_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('channel_key'),
    sa.UniqueConstraint('channel_name'),
    schema='raw_analytics'
    )
    op.create_index(op.f('ix_raw_analytics_dim_channels_channel_key'), 'dim_channels', ['channel_key'], unique=False, schema='raw_analytics')
    op.create_table('dim_dates',
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.String(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date_id'),
    schema='raw_analytics'
    )
    op.create_table('fct_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('channel_key', sa.Integer(), nullable=True),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('message_length', sa.Integer(), nullable=True),
    sa.Column('has_image', sa.Boolean(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['channel_key'], ['raw_analytics.dim_channels.channel_key'], ),
    sa.ForeignKeyConstraint(['date_id'], ['raw_analytics.dim_dates.date_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    schema='raw_analytics'
    )
    op.create_index(op.f('ix_raw_analytics_fct_messages_message_id'), 'fct_messages', ['message_id'], unique=False, schema='raw_analytics')
    op.create_table('fct_image_detections',
    sa.Column('detection_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('detected_object_class', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['raw_analytics.fct_messages.message_id'], ),
    sa.PrimaryKeyConstraint('detection_id'),
    schema='raw'
    )
    op.create_index(op.f('ix_raw_fct_image_detections_detection_id'), 'fct_image_detections', ['detection_id'], unique=False, schema='raw')
    op.drop_index(op.f('ix_fct_messages_message_id'), table_name='fct_messages')
    op.drop_table('fct_messages')
    op.drop_table('dim_dates')
    op.drop_index(op.f('ix_dim_channels_channel_id'), table_name='dim_channels')
    op.drop_table('dim_channels')
    op.drop_index(op.f('ix_fct_image_detections_detection_id'), table_name='fct_image_detections')
    op.drop_table('fct_image_detections')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fct_image_detections',
    sa.Column('detection_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detected_object_class', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['fct_messages.message_id'], name=op.f('fct_image_detections_message_id_fkey')),
    sa.PrimaryKeyConstraint('detection_id', name=op.f('fct_image_detections_pkey'))
    )
    op.create_index(op.f('ix_fct_image_detections_detection_id'), 'fct_image_detections', ['detection_id'], unique=False)
    op.create_table('dim_channels',
    sa.Column('channel_id', sa.INTEGER(), server_default=sa.text("nextval('dim_channels_channel_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('channel_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('channel_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('channel_id', name='dim_channels_pkey'),
    sa.UniqueConstraint('channel_name', name='dim_channels_channel_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_dim_channels_channel_id'), 'dim_channels', ['channel_id'], unique=False)
    op.create_table('dim_dates',
    sa.Column('date_id', sa.INTEGER(), server_default=sa.text("nextval('dim_dates_date_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weekday', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('date_id', name='dim_dates_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('fct_messages',
    sa.Column('message_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('has_image', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['dim_channels.channel_id'], name=op.f('fct_messages_channel_id_fkey')),
    sa.ForeignKeyConstraint(['date_id'], ['dim_dates.date_id'], name=op.f('fct_messages_date_id_fkey')),
    sa.PrimaryKeyConstraint('message_id', name=op.f('fct_messages_pkey'))
    )
    op.create_index(op.f('ix_fct_messages_message_id'), 'fct_messages', ['message_id'], unique=False)
    op.drop_index(op.f('ix_raw_fct_image_detections_detection_id'), table_name='fct_image_detections', schema='raw')
    op.drop_table('fct_image_detections', schema='raw')
    op.drop_index(op.f('ix_raw_analytics_fct_messages_message_id'), table_name='fct_messages', schema='raw_analytics')
    op.drop_table('fct_messages', schema='raw_analytics')
    op.drop_table('dim_dates', schema='raw_analytics')
    op.drop_index(op.f('ix_raw_analytics_dim_channels_channel_key'), table_name='dim_channels', schema='raw_analytics')
    op.drop_table('dim_channels', schema='raw_analytics')
    # ### end Alembic commands ###
